<?php

namespace App\Filament\Resources\PointResource\Pages;

use App\Filament\Resources\PointResource;
use Filament\Actions;
use Filament\Notifications\Notification;
use Filament\Resources\Pages\CreateRecord;

class CreatePoint extends CreateRecord
{
    protected static string $resource = PointResource::class;
    protected function getCreateFormAction(): \Filament\Actions\Action
    {
        return parent::getCreateFormAction()
        ->label('Үүсгэх');
    }
    protected  function getRedirectUrl(): string
    {
        return PointResource::getUrl('index'); // TODO: Change the autogenerated stub
    }
    protected function getNotification(): ?Notification
    {
        return Notification::make()
            ->title('Амжилттай')
            ->success()
            ->body('Амжилттай үүсгэгдлээ');
    }
}
