<?php

namespace App\Filament\App\Resources\EmployeeResource\Pages;

use App\Filament\App\Resources\EmployeeResource;
use Filament\Actions;
use Filament\Notifications\Notification;
use Filament\Resources\Pages\CreateRecord;

class CreateEmployee extends CreateRecord
{
    protected static string $resource = EmployeeResource::class;
    protected static ?string $title = 'Шинэ ажилтан үүсгэх';
    protected function getCreateFormAction(): \Filament\Actions\Action
    {
        return parent::getCreateFormAction()
            ->label('Үүсгэх');
    }
    protected  function getRedirectUrl(): string
    {
        return \App\Filament\Resources\EmployeeResource ::getUrl('index'); // TODO: Change the autogenerated stub
    }
    protected  function getCreatedNotification(): ?Notification
    {
        return Notification::make()
            ->title('Мэдээлэл')
            ->success()
            ->body('Мэдээлэл амжилттай хадаглагдлаа.')
            ->duration(3000)
            ->send();
    }
}
