<?php

namespace App\Filament\App\Resources\EmployeeResource\Pages;

use App\Filament\App\Resources\EmployeeResource;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;

class CreateEmployee extends CreateRecord
{
    protected static string $resource = EmployeeResource::class;
    protected function getCreateFormAction(): \Filament\Actions\Action
    {
        return parent::getCreateFormAction()
            ->label('Үүсгэх');
    }
    protected  function getRedirectUrl(): string
    {
        return \App\Filament\Resources\EmployeeResource ::getUrl('index'); // TODO: Change the autogenerated stub
    }
}
