<?php

namespace App\Filament\Resources\TechTypeResource\Pages;

use App\Filament\Resources\TechTypeResource;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;

class CreateTechType extends CreateRecord
{
    protected static string $resource = TechTypeResource::class;
    protected static ?string $title = 'Техникийн төрөл үүсгэх';
    protected function getCreateFormAction(): \Filament\Actions\Action
    {
        return parent::getCreateFormAction()
            ->label('Үүсгэх');
    }
    protected  function getRedirectUrl(): string
    {
        return TechTypeResource::getUrl('index'); // TODO: Change the autogenerated stub
    }
}
