<?php

namespace App\Filament\Resources\RegionResource\Pages;

use App\Filament\Resources\RegionResource;
use Filament\Actions;
use Filament\Notifications\Notification;
use Filament\Resources\Pages\CreateRecord;

class CreateRegion extends CreateRecord
{
    protected static string $resource = RegionResource::class;
    protected static ?string $title = 'Харьяалал үүсгэх';
     protected function getCreateFormAction(): \Filament\Actions\Action
    {
        return parent::getCreateFormAction()
        ->label('Үүсгэх');
    }
    protected  function getRedirectUrl(): string
    {
        return RegionResource::getUrl('index'); // TODO: Change the autogenerated stub
    }
    protected  function getCreatedNotification(): ?Notification
    {
        return Notification::make()
            ->title('Мэдээлэл')
            ->success()
            ->body('Мэдээлэл амжилттай хадаглагдлаа.')
            ->duration(3000)
            ->send();
    }
}
