<?php

namespace App\Filament\Resources\TechCategoryResource\Pages;

use App\Filament\Resources\TechCategoryResource;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;

class CreateTechCategory extends CreateRecord
{
    protected static string $resource = TechCategoryResource::class;
    protected static ?string $title = 'Техникийн ангилал үүсгэх';
    protected function getCreateFormAction(): \Filament\Actions\Action
    {
        return parent::getCreateFormAction()
            ->label('Үүсгэх');
    }
    protected  function getRedirectUrl(): string
    {
        return TechCategoryResource::getUrl('index'); // TODO: Change the autogenerated stub
    }
}
