<?php

namespace App\Filament\Resources\SubCompanyResource\Pages;

use App\Filament\Resources\SubCompanyResource;
use Filament\Actions;
use Filament\Notifications\Notification;
use Filament\Resources\Pages\CreateRecord;

class CreateSubCompany extends CreateRecord
{
    protected static string $resource = SubCompanyResource::class;
    protected static ?string $title = 'Туслан гүйцэтгэгч компани үүсгэх';
    protected function getCreateFormAction(): \Filament\Actions\Action
    {
        return parent::getCreateFormAction()
        ->label('Үүсгэх');
    }
    protected  function getRedirectUrl(): string
    {
        return SubCompanyResource::getUrl('index'); // TODO: Change the autogenerated stub
    }
    protected  function getCreatedNotification(): ?Notification
    {
        return Notification::make()
            ->title('Мэдээлэл')
            ->success()
            ->body('Мэдээлэл амжилттай хадаглагдлаа.')
            ->duration(3000)
            ->send();
    }
}
