<?php

namespace App\Filament\Resources\TechMarkResource\Pages;

use App\Filament\Resources\TechMarkResource;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;

class CreateTechMark extends CreateRecord
{
    protected static string $resource = TechMarkResource::class;
    protected static ?string $title = 'Техникийн марк үүсгэх';
    protected function getCreateFormAction(): \Filament\Actions\Action
    {
        return parent::getCreateFormAction()
            ->label('Үүсгэх');
    }
    protected  function getRedirectUrl(): string
    {
        return TechMarkResource::getUrl('index'); // TODO: Change the autogenerated stub
    }
}
